#!/usr/bin/env python3
"""
PipeDreams - A whimsical PipeWire audio control panel
Because audio configuration should be fun!
"""

import sys
import subprocess
import json
import os
from pathlib import Path
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QSlider, QPushButton, QComboBox, QGroupBox, QMessageBox,
    QTabWidget, QSpinBox, QCheckBox, QTextEdit, QScrollArea
)
from PyQt6.QtCore import Qt, QTimer, QPropertyAnimation, QEasingCurve
from PyQt6.QtGui import QFont, QPalette, QColor, QIcon


class PipeWireController:
    """Backend for controlling PipeWire settings"""

    def __init__(self):
        self.config_dir = Path.home() / ".config" / "pipewire" / "pipewire.conf.d"
        self.config_file = self.config_dir / "99-pipedreams.conf"

    def ensure_config_dir(self):
        """Create config directory if it doesn't exist"""
        self.config_dir.mkdir(parents=True, exist_ok=True)

    def get_devices(self):
        """Get list of audio devices"""
        try:
            # Try pactl first
            result = subprocess.run(
                ['pactl', 'list', 'sinks', 'short'],
                capture_output=True, text=True, check=True,
                env={**os.environ, 'XDG_RUNTIME_DIR': f'/run/user/{os.getuid()}'}
            )
            devices = []
            for line in result.stdout.strip().split('\n'):
                if line:
                    parts = line.split('\t')
                    if len(parts) >= 2:
                        devices.append({'id': parts[0], 'name': parts[1]})
            return devices
        except subprocess.CalledProcessError:
            # Fallback to pw-cli
            try:
                result = subprocess.run(
                    ['pw-cli', 'ls', 'Node'],
                    capture_output=True, text=True, check=True,
                    env={**os.environ, 'XDG_RUNTIME_DIR': f'/run/user/{os.getuid()}'}
                )
                # Parse pw-cli output (basic parsing)
                devices = []
                return devices  # Simplified for now
            except subprocess.CalledProcessError:
                return []

    def get_sources(self):
        """Get list of audio input sources"""
        try:
            result = subprocess.run(
                ['pactl', 'list', 'sources', 'short'],
                capture_output=True, text=True, check=True
            )
            sources = []
            for line in result.stdout.strip().split('\n'):
                if line:
                    parts = line.split('\t')
                    if len(parts) >= 2:
                        sources.append({'id': parts[0], 'name': parts[1]})
            return sources
        except subprocess.CalledProcessError:
            return []

    def get_sink_volume(self, sink_id):
        """Get volume for a specific sink"""
        try:
            result = subprocess.run(
                ['pactl', 'get-sink-volume', sink_id],
                capture_output=True, text=True, check=True
            )
            # Parse output like: "Volume: front-left: 65536 / 100% / 0.00 dB"
            if '%' in result.stdout:
                percent = result.stdout.split('%')[0].split()[-1]
                return int(percent)
        except (subprocess.CalledProcessError, ValueError, IndexError):
            pass
        return 50

    def set_sink_volume(self, sink_id, volume):
        """Set volume for a specific sink (0-100)"""
        try:
            subprocess.run(
                ['pactl', 'set-sink-volume', sink_id, f'{volume}%'],
                check=True
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def apply_settings(self, sample_rate, quantum, min_quantum, max_quantum):
        """Apply PipeWire settings"""
        self.ensure_config_dir()

        config = f"""# Generated by PipeDreams
context.properties = {{
    default.clock.rate = {sample_rate}
    default.clock.quantum = {quantum}
    default.clock.min-quantum = {min_quantum}
    default.clock.max-quantum = {max_quantum}
}}
"""

        try:
            with open(self.config_file, 'w') as f:
                f.write(config)
            return True
        except Exception as e:
            print(f"Error writing config: {e}")
            return False

    def restart_pipewire(self):
        """Restart PipeWire services"""
        try:
            subprocess.run(
                ['systemctl', '--user', 'restart', 'pipewire', 'pipewire-pulse', 'wireplumber'],
                check=True
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def get_current_settings(self):
        """Get current PipeWire settings"""
        try:
            result = subprocess.run(
                ['pw-cli', 'info', '0'],
                capture_output=True, text=True, check=True
            )
            # Parse the output for current settings
            settings = {
                'sample_rate': 48000,
                'quantum': 1024,
            }

            for line in result.stdout.split('\n'):
                if 'clock.rate' in line and '=' in line:
                    try:
                        settings['sample_rate'] = int(line.split('=')[1].strip())
                    except (ValueError, IndexError):
                        pass
                elif 'clock.quantum' in line and '=' in line:
                    try:
                        settings['quantum'] = int(line.split('=')[1].strip())
                    except (ValueError, IndexError):
                        pass

            return settings
        except subprocess.CalledProcessError:
            return {'sample_rate': 48000, 'quantum': 1024}


class PipeDreamsWindow(QMainWindow):
    """Main application window"""

    def __init__(self):
        super().__init__()
        self.controller = PipeWireController()
        self.init_ui()
        self.load_current_settings()

        # Auto-refresh timer
        self.refresh_timer = QTimer()
        self.refresh_timer.timeout.connect(self.refresh_devices)
        self.refresh_timer.start(2000)  # Refresh every 2 seconds

    def init_ui(self):
        """Initialize the user interface"""
        self.setWindowTitle("🎵 PipeDreams - Your Audio Buddy 🎵")
        self.setMinimumSize(800, 600)

        # Apply cute color scheme
        self.apply_theme()

        # Main widget and layout
        main_widget = QWidget()
        self.setCentralWidget(main_widget)
        layout = QVBoxLayout(main_widget)

        # Header
        header = QLabel("🌈 PipeDreams 🌈")
        header.setFont(QFont("Arial", 24, QFont.Weight.Bold))
        header.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(header)

        subtitle = QLabel("Where audio dreams come true!")
        subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        subtitle.setFont(QFont("Arial", 10))
        layout.addWidget(subtitle)

        # Create tabs
        tabs = QTabWidget()
        tabs.addTab(self.create_devices_tab(), "🎧 Devices")
        tabs.addTab(self.create_performance_tab(), "⚡ Performance")
        tabs.addTab(self.create_advanced_tab(), "🔧 Advanced")
        tabs.addTab(self.create_info_tab(), "ℹ️ Info")
        layout.addWidget(tabs)

        # Status bar
        self.status_label = QLabel("Ready to make your audio dreams come true!")
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.status_label.setStyleSheet("padding: 10px; background-color: rgba(100, 200, 255, 0.2); border-radius: 5px;")
        layout.addWidget(self.status_label)

    def apply_theme(self):
        """Apply a cute color theme"""
        palette = QPalette()

        # Soft pastel colors
        palette.setColor(QPalette.ColorRole.Window, QColor(240, 245, 255))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(50, 50, 80))
        palette.setColor(QPalette.ColorRole.Base, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(230, 240, 255))
        palette.setColor(QPalette.ColorRole.Button, QColor(200, 220, 255))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(50, 50, 80))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(100, 150, 255))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))

        self.setPalette(palette)

        # Additional styling
        self.setStyleSheet("""
            QGroupBox {
                font-weight: bold;
                border: 2px solid #B0D0FF;
                border-radius: 8px;
                margin-top: 10px;
                padding-top: 10px;
                background-color: rgba(255, 255, 255, 0.5);
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px;
            }
            QPushButton {
                background-color: #90C8FF;
                border: none;
                border-radius: 5px;
                padding: 8px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #70B0FF;
            }
            QPushButton:pressed {
                background-color: #5098FF;
            }
            QSlider::groove:horizontal {
                height: 8px;
                background: #D0E0FF;
                border-radius: 4px;
            }
            QSlider::handle:horizontal {
                background: #5098FF;
                width: 18px;
                margin: -5px 0;
                border-radius: 9px;
            }
            QSlider::handle:horizontal:hover {
                background: #70B0FF;
            }
        """)

    def create_devices_tab(self):
        """Create the devices control tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)

        # Output devices
        output_group = QGroupBox("🔊 Output Devices (Sinks)")
        output_layout = QVBoxLayout()

        self.output_combo = QComboBox()
        output_layout.addWidget(QLabel("Select Output Device:"))
        output_layout.addWidget(self.output_combo)

        # Volume control
        volume_layout = QHBoxLayout()
        volume_layout.addWidget(QLabel("Volume:"))
        self.output_volume = QSlider(Qt.Orientation.Horizontal)
        self.output_volume.setRange(0, 100)
        self.output_volume.setValue(50)
        self.output_volume.valueChanged.connect(self.on_volume_changed)
        volume_layout.addWidget(self.output_volume)
        self.volume_label = QLabel("50%")
        volume_layout.addWidget(self.volume_label)
        output_layout.addLayout(volume_layout)

        output_group.setLayout(output_layout)
        layout.addWidget(output_group)

        # Input devices
        input_group = QGroupBox("🎤 Input Devices (Sources)")
        input_layout = QVBoxLayout()

        self.input_combo = QComboBox()
        input_layout.addWidget(QLabel("Select Input Device:"))
        input_layout.addWidget(self.input_combo)

        input_group.setLayout(input_layout)
        layout.addWidget(input_group)

        # Refresh button
        refresh_btn = QPushButton("🔄 Refresh Devices")
        refresh_btn.clicked.connect(self.refresh_devices)
        layout.addWidget(refresh_btn)

        layout.addStretch()
        return widget

    def create_performance_tab(self):
        """Create the performance settings tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)

        # Sample rate
        sample_group = QGroupBox("🎼 Sample Rate")
        sample_layout = QVBoxLayout()

        sample_layout.addWidget(QLabel("Select sample rate (Hz):"))
        self.sample_rate = QComboBox()
        self.sample_rate.addItems(['44100', '48000', '88200', '96000', '192000'])
        self.sample_rate.setCurrentText('48000')
        sample_layout.addWidget(self.sample_rate)

        info_label = QLabel("💡 48000 Hz is recommended for most use cases")
        info_label.setStyleSheet("font-size: 10px; color: #666;")
        sample_layout.addWidget(info_label)

        sample_group.setLayout(sample_layout)
        layout.addWidget(sample_group)

        # Buffer size (quantum)
        buffer_group = QGroupBox("⏱️ Latency Settings")
        buffer_layout = QVBoxLayout()

        buffer_layout.addWidget(QLabel("Buffer Size (Quantum):"))
        quantum_layout = QHBoxLayout()
        self.quantum = QSpinBox()
        self.quantum.setRange(64, 8192)
        self.quantum.setValue(1024)
        self.quantum.setSuffix(" samples")
        quantum_layout.addWidget(self.quantum)
        buffer_layout.addLayout(quantum_layout)

        buffer_layout.addWidget(QLabel("Minimum Quantum:"))
        min_quantum_layout = QHBoxLayout()
        self.min_quantum = QSpinBox()
        self.min_quantum.setRange(32, 4096)
        self.min_quantum.setValue(256)
        self.min_quantum.setSuffix(" samples")
        min_quantum_layout.addWidget(self.min_quantum)
        buffer_layout.addLayout(min_quantum_layout)

        buffer_layout.addWidget(QLabel("Maximum Quantum:"))
        max_quantum_layout = QHBoxLayout()
        self.max_quantum = QSpinBox()
        self.max_quantum.setRange(128, 16384)
        self.max_quantum.setValue(2048)
        self.max_quantum.setSuffix(" samples")
        max_quantum_layout.addWidget(self.max_quantum)
        buffer_layout.addLayout(max_quantum_layout)

        info_label = QLabel("💡 Lower values = less latency but more CPU usage\n"
                          "💡 Higher values = more latency but smoother playback")
        info_label.setStyleSheet("font-size: 10px; color: #666;")
        buffer_layout.addWidget(info_label)

        buffer_group.setLayout(buffer_layout)
        layout.addWidget(buffer_group)

        # Preset buttons
        preset_group = QGroupBox("🎯 Quick Presets")
        preset_layout = QHBoxLayout()

        gaming_btn = QPushButton("🎮 Gaming\n(Low Latency)")
        gaming_btn.clicked.connect(lambda: self.apply_preset('gaming'))
        preset_layout.addWidget(gaming_btn)

        music_btn = QPushButton("🎵 Music Production\n(Ultra Low)")
        music_btn.clicked.connect(lambda: self.apply_preset('music'))
        preset_layout.addWidget(music_btn)

        streaming_btn = QPushButton("📺 Streaming\n(Balanced)")
        streaming_btn.clicked.connect(lambda: self.apply_preset('streaming'))
        preset_layout.addWidget(streaming_btn)

        quality_btn = QPushButton("💎 Quality\n(High Buffer)")
        quality_btn.clicked.connect(lambda: self.apply_preset('quality'))
        preset_layout.addWidget(quality_btn)

        preset_group.setLayout(preset_layout)
        layout.addWidget(preset_group)

        # Apply button
        apply_btn = QPushButton("✨ Apply Settings & Restart PipeWire ✨")
        apply_btn.setStyleSheet("QPushButton { padding: 15px; font-size: 14px; }")
        apply_btn.clicked.connect(self.apply_settings)
        layout.addWidget(apply_btn)

        layout.addStretch()
        return widget

    def create_advanced_tab(self):
        """Create advanced settings tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)

        info_group = QGroupBox("⚙️ Configuration File")
        info_layout = QVBoxLayout()

        info_layout.addWidget(QLabel(f"Config location: {self.controller.config_file}"))

        view_btn = QPushButton("👀 View Current Config")
        view_btn.clicked.connect(self.view_config)
        info_layout.addWidget(view_btn)

        self.config_text = QTextEdit()
        self.config_text.setReadOnly(True)
        self.config_text.setMaximumHeight(200)
        info_layout.addWidget(self.config_text)

        info_group.setLayout(info_layout)
        layout.addWidget(info_group)

        # System info
        system_group = QGroupBox("🖥️ System Information")
        system_layout = QVBoxLayout()

        self.system_info = QTextEdit()
        self.system_info.setReadOnly(True)
        self.system_info.setMaximumHeight(150)
        system_layout.addWidget(self.system_info)

        refresh_info_btn = QPushButton("🔄 Refresh System Info")
        refresh_info_btn.clicked.connect(self.update_system_info)
        system_layout.addWidget(refresh_info_btn)

        system_group.setLayout(system_layout)
        layout.addWidget(system_group)

        # Danger zone
        danger_group = QGroupBox("⚠️ Danger Zone")
        danger_layout = QVBoxLayout()

        reset_btn = QPushButton("🗑️ Delete Custom Config")
        reset_btn.clicked.connect(self.delete_config)
        reset_btn.setStyleSheet("QPushButton { background-color: #FFB0B0; }")
        danger_layout.addWidget(reset_btn)

        danger_group.setLayout(danger_layout)
        layout.addWidget(danger_group)

        layout.addStretch()
        return widget

    def create_info_tab(self):
        """Create info/about tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll_content = QWidget()
        scroll_layout = QVBoxLayout(scroll_content)

        info_text = """
        <h2>🌈 Welcome to PipeDreams! 🌈</h2>

        <p><b>PipeDreams</b> is your friendly audio control panel for PipeWire on Linux!</p>

        <h3>✨ Features:</h3>
        <ul>
            <li>🎧 Easy device selection and volume control</li>
            <li>⚡ Performance tuning for gaming, music, and streaming</li>
            <li>🎯 One-click presets for common use cases</li>
            <li>🔧 Advanced configuration options</li>
            <li>💖 A cute and friendly interface!</li>
        </ul>

        <h3>📚 Quick Guide:</h3>
        <ul>
            <li><b>Devices Tab:</b> Control your audio devices and volume</li>
            <li><b>Performance Tab:</b> Adjust latency and buffer settings</li>
            <li><b>Advanced Tab:</b> View configs and system information</li>
        </ul>

        <h3>🎯 Preset Recommendations:</h3>
        <ul>
            <li><b>Gaming:</b> Low latency for competitive gaming</li>
            <li><b>Music Production:</b> Ultra-low latency for recording</li>
            <li><b>Streaming:</b> Balanced settings for broadcasting</li>
            <li><b>Quality:</b> Higher buffer for smooth playback</li>
        </ul>

        <h3>⚠️ Important Notes:</h3>
        <ul>
            <li>Changes require PipeWire restart to take effect</li>
            <li>Lower latency = higher CPU usage</li>
            <li>If you hear crackling, increase the buffer size</li>
            <li>48000 Hz sample rate works for most scenarios</li>
        </ul>

        <h3>💡 Tips:</h3>
        <ul>
            <li>Start with presets, then fine-tune if needed</li>
            <li>Check the Advanced tab for current settings</li>
            <li>Your custom config is saved separately from system defaults</li>
        </ul>

        <hr>
        <p align="center">
            <i>Made with 💖 for the Linux audio community</i><br>
            <small>Because configuring audio shouldn't be a nightmare!</small>
        </p>
        """

        info_label = QLabel(info_text)
        info_label.setWordWrap(True)
        info_label.setTextFormat(Qt.TextFormat.RichText)
        scroll_layout.addWidget(info_label)

        scroll.setWidget(scroll_content)
        layout.addWidget(scroll)

        return widget

    def refresh_devices(self):
        """Refresh the list of audio devices"""
        # Save current selections
        current_output = self.output_combo.currentText()
        current_input = self.input_combo.currentText()

        # Refresh outputs
        self.output_combo.clear()
        devices = self.controller.get_devices()
        for device in devices:
            self.output_combo.addItem(f"{device['name']} (#{device['id']})", device['id'])

        # Restore selection if possible
        idx = self.output_combo.findText(current_output)
        if idx >= 0:
            self.output_combo.setCurrentIndex(idx)

        # Refresh inputs
        self.input_combo.clear()
        sources = self.controller.get_sources()
        for source in sources:
            self.input_combo.addItem(f"{source['name']} (#{source['id']})", source['id'])

        # Restore selection if possible
        idx = self.input_combo.findText(current_input)
        if idx >= 0:
            self.input_combo.setCurrentIndex(idx)

        # Update volume for current device
        if self.output_combo.currentData():
            volume = self.controller.get_sink_volume(self.output_combo.currentData())
            self.output_volume.setValue(volume)

    def on_volume_changed(self, value):
        """Handle volume slider changes"""
        self.volume_label.setText(f"{value}%")

        # Apply volume to current device
        if self.output_combo.currentData():
            self.controller.set_sink_volume(self.output_combo.currentData(), value)

    def apply_preset(self, preset):
        """Apply a performance preset"""
        presets = {
            'gaming': {
                'sample_rate': 48000,
                'quantum': 512,
                'min_quantum': 256,
                'max_quantum': 1024,
            },
            'music': {
                'sample_rate': 48000,
                'quantum': 256,
                'min_quantum': 128,
                'max_quantum': 512,
            },
            'streaming': {
                'sample_rate': 48000,
                'quantum': 1024,
                'min_quantum': 512,
                'max_quantum': 2048,
            },
            'quality': {
                'sample_rate': 48000,
                'quantum': 2048,
                'min_quantum': 1024,
                'max_quantum': 4096,
            },
        }

        if preset in presets:
            config = presets[preset]
            self.sample_rate.setCurrentText(str(config['sample_rate']))
            self.quantum.setValue(config['quantum'])
            self.min_quantum.setValue(config['min_quantum'])
            self.max_quantum.setValue(config['max_quantum'])

            self.set_status(f"✨ Applied {preset.title()} preset! Click 'Apply Settings' to activate.", "info")

    def apply_settings(self):
        """Apply the current settings"""
        sample_rate = int(self.sample_rate.currentText())
        quantum = self.quantum.value()
        min_quantum = self.min_quantum.value()
        max_quantum = self.max_quantum.value()

        # Validation
        if min_quantum > quantum:
            QMessageBox.warning(self, "Invalid Settings",
                              "Minimum quantum cannot be larger than quantum!")
            return

        if quantum > max_quantum:
            QMessageBox.warning(self, "Invalid Settings",
                              "Quantum cannot be larger than maximum quantum!")
            return

        # Apply settings
        if self.controller.apply_settings(sample_rate, quantum, min_quantum, max_quantum):
            # Ask to restart
            reply = QMessageBox.question(
                self, "Restart PipeWire?",
                "Settings saved! Restart PipeWire now to apply changes?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
            )

            if reply == QMessageBox.StandardButton.Yes:
                if self.controller.restart_pipewire():
                    self.set_status("🎉 Settings applied and PipeWire restarted!", "success")
                    QTimer.singleShot(3000, lambda: self.load_current_settings())
                else:
                    self.set_status("⚠️ Failed to restart PipeWire. Try manually: systemctl --user restart pipewire", "error")
            else:
                self.set_status("💾 Settings saved. Restart PipeWire manually to apply.", "info")
        else:
            self.set_status("❌ Failed to save settings!", "error")

    def view_config(self):
        """View the current configuration file"""
        if self.controller.config_file.exists():
            with open(self.controller.config_file, 'r') as f:
                self.config_text.setPlainText(f.read())
        else:
            self.config_text.setPlainText("No custom configuration file found yet.\nApply settings to create one!")

    def delete_config(self):
        """Delete the custom configuration"""
        reply = QMessageBox.question(
            self, "Delete Config?",
            "Are you sure you want to delete your custom configuration?\nPipeWire will use system defaults.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )

        if reply == QMessageBox.StandardButton.Yes:
            try:
                if self.controller.config_file.exists():
                    self.controller.config_file.unlink()
                    self.set_status("🗑️ Configuration deleted. Restart PipeWire to use defaults.", "info")
                    self.config_text.clear()
                else:
                    self.set_status("No configuration file to delete.", "info")
            except Exception as e:
                self.set_status(f"❌ Error deleting config: {e}", "error")

    def update_system_info(self):
        """Update system information display"""
        current = self.controller.get_current_settings()

        info = f"""Sample Rate: {current['sample_rate']} Hz
Quantum: {current['quantum']} samples
Latency: ~{(current['quantum'] / current['sample_rate'] * 1000):.1f} ms

Config Directory: {self.controller.config_dir}
Config File Exists: {'Yes' if self.controller.config_file.exists() else 'No'}
"""

        self.system_info.setPlainText(info)

    def load_current_settings(self):
        """Load current settings into the UI"""
        current = self.controller.get_current_settings()

        # Update UI
        self.sample_rate.setCurrentText(str(current['sample_rate']))
        self.quantum.setValue(current['quantum'])

        # Refresh devices
        self.refresh_devices()

        # Update info
        self.update_system_info()
        self.view_config()

    def set_status(self, message, status_type="info"):
        """Set status message with color coding"""
        colors = {
            "info": "rgba(100, 200, 255, 0.3)",
            "success": "rgba(100, 255, 150, 0.3)",
            "error": "rgba(255, 100, 100, 0.3)",
        }

        color = colors.get(status_type, colors["info"])
        self.status_label.setStyleSheet(f"padding: 10px; background-color: {color}; border-radius: 5px;")
        self.status_label.setText(message)


def main():
    app = QApplication(sys.argv)

    # Set application info
    app.setApplicationName("PipeDreams")
    app.setOrganizationName("PipeDreams")

    window = PipeDreamsWindow()
    window.show()

    sys.exit(app.exec())


if __name__ == '__main__':
    main()
